highlighter: pygments
markdown: redcarpet # github flavored markdown

redcarpet:
    no_fenced_code_blocks: true # enable original fenced code block(```)

mode: dev
url: http://unifreak.github.io/
devurl: http://localhost:4000/
name: UniFreak
title: UniFreak | Another yet unique freak is showing a freakshow
description: "Fanghao's personal weblog, on coding or such stuff"

my:
    displayName: UniFreak
    realName: FangHao
    contact:
        qq: 744910240
        email: fanghao90s@gmail.com
        github: http://www.github.com/UniFreak
        tel: 15671542698
        address:
            country: China
            state: Hubei
            city: Wuhan
            distribute: Hongshan
            postcode: 450000
            cell: "XuefuJiayuan"

collections:
    qqGroupGuide:
        output: true

defaults:
  # - scope:
  #       path: ""
  #       type: "posts"
  #   values:
  #       permalink: /:categories/:title/
  # - scope:
  #       path: ""
  #       type: "qqGroupGuide"
  #   values:
  #       permalink: /:collection/:title/
  - scope:
        path: ""
        type: "qqGroupGuide"
    values:
        layout: markdown_reader