highlighter: pygments
markdown: redcarpet # github flavored markdown

redcarpet:
    no_fenced_code_blocks: true # enable original fenced code block(```)

paginate: 7
paginate_path: "page:num"

mode: dev
# mode: product
url: http://unifreak.github.io/
devurl: http://localhost:4000/
name: UniFreak
title: UniFreak | Another yet unique freak is showing a freakshow
description: "Fanghao's personal weblog, on coding or such stuff"

my:
    displayName: UniFreak
    realName: FangHao
    realName_cn: 方浩
    jobTitle: "PHP Coder"
    contact:
        qq: 744910240
        email: fanghao90s@gmail.com
        github: http://www.github.com/UniFreak
        qzone: http://744910240.qzone.qq.com
        pinterest: https://www.pinterest.com/miblah/
        tel: 15671542698
        address:
            country: China
            state: Hubei
            city: Wuhan
            distribute: Hongshan
            postcode: 450000
            cell: "XuefuJiayuan"
    skills:
        frontend: ["HTML | Markdown", "CSS | SASS", "JS | jQuery", "Bootstrap"]
        backend: ["PHP", "MySQL", "Redis", "Regex", "Laravel", "OSC"]
        tools: ["Sublime Text", "Git | Github", "Linux", "Jekyll | Liquid"]

collections:
    qqGroupGuide:
        output: true

defaults:
  # - scope:
  #       path: ""
  #       type: "posts"
  #   values:
  #       permalink: /:categories/:title/
  # - scope:
  #       path: ""
  #       type: "qqGroupGuide"
  #   values:
  #       permalink: /:collection/:title/
  - scope:
        path: ""
        type: "qqGroupGuide"
    values:
        layout: markdown_reader