highlighter: pygments
markdown: redcarpet # github flavored markdown

redcarpet:
    no_fenced_code_blocks: true # enable original fenced code block(```)

url: http://unifreak.github.io/
name: UniFreak
tagLine: On the way to death
title: UniFreak | Another yet unique freak is showing a freakshow
description: "Fanghao's personal weblog, on coding or such stuff"
authorName: FangHao
authorTitle: PHP Coder

collections:
    qqGroupGuide:
        output: true

defaults:
  # - scope:
  #       path: ""
  #       type: "posts"
  #   values:
  #       permalink: /:categories/:title/
  # - scope:
  #       path: ""
  #       type: "qqGroupGuide"
  #   values:
  #       permalink: /:collection/:title/
  - scope:
        path: ""
        type: "qqGroupGuide"
    values:
        layout: markdown_reader