# highlighter: pygments
highlighter: rouge

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# markdown: kramdown
# kramdown:
#     input: GFM
#     syntax_highlighter: rouge

gems: [jekyll-paginate]
paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

# mode: dev
mode: product
url: https://unifreak.github.io/
devurl: http://localhost:4000/
name: UniFreak
title: UniFreak | Another yet unique freak is showing a freakshow
description: "Fanghao's personal weblog, on coding or such stuff"

my:
    displayName: BernoYoun
    realName: BernoYoun
    realName_cn: BernoYoun
    jobTitle: "Student Developer"
    contact:
        email: gudwls1530@gmail.com
        github: http://www.github.com/0113bernoyoun
    skills:
        App: ["App Inventor", "Android"]
        ML: ["Keras"]
        HardWare: ["Raspberry PI","Arduino"]
        frontend: ["HTML | Markdown", "JS | jQuery"]
        backend: ["PHP", "MySQL", "Node.JS", "Regex"]
        Language: ["Python", "JAVA", "C++"]
        tools: ["Sublime Text", "Git | Github", "Linux | ubuntu", "Visual Studio", "Eclipse", "Pycharm" ]

collections:
    qqGroupGuide:
        output: true

defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        excerpt: "{{ page.content }} | slice: 0 300"
  - scope:
        path: ""
        type: "qqGroupGuide"
    values:
        layout: markdownreader_bare
