url: http://unifreak.github.io/
highlighter: pygments
markdown: redcarpet # github flavored markdown

redcarpet:
    no_fenced_code_blocks: true # enable original fenced code block(```)

collections:
    qqGroupGuide:
        output: true


defaults:
  # - scope:
  #       path: ""
  #       type: "posts"
  #   values:
  #       permalink: /:categories/:title/
  # - scope:
  #       path: ""
  #       type: "qqGroupGuide"
  #   values:
  #       permalink: /:collection/:title/
  - scope:
        path: ""
        type: "qqGroupGuide"
    values:
        permalink: /:title.html
        layout: markdown_reader